export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_STATE_REQUEST = "ADD_STATE_REQUEST"
export const ADD_FILTER_CATEGORY = "ADD_FILTER_CATEGORY"
export const ADD_FILTER_COLOR = "ADD_FILTER_COLOR"